# Run pre-commit autoupdate every day at midnight
# and create a pull request if any changes

name: Pre-commit auto-update

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch: # to trigger manually

permissions:
  contents: read

jobs:
  auto-update:
    if:  ${{ inputs.GH_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Updated Hooks
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: $GH_TOKEN
          branch: update/pre-commit-autoupdate
          title: ⬆️Update pre-commit hooks
          commit-message: ⬆️updated pre-commit hooks
          body: ✨Update versions of tools in pre-commit configs to latest version
          labels: pre-commit✨
